import Head from 'next/head'
import Page from "../components/modules/Page";
import {lightTheme} from "../utils/styles/themes";

export default function Home() {
  return (
    <Page theme={lightTheme} meta={{title: 'Hello', description: 'World'}}>
      {/*<Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>*/}
        asd
    </Page>
  )
}
