name: Dev Build & Test
on:
  pull_request:
    branches:
      - dev
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: npm ci
      - name: Run Linter
        run: yarn lint
      - name: Build
        run: yarn build
